odom_frame: odom
base_link_frame: base_link
world_frame: odom

publish_tf: true
publish_acceleration: true

two_d_mode: false

predict_to_current_time: true

frequency: 50

imu0: imu/data
imu0_remove_gravitational_acceleration: true
imu0_config: [true, true, true,
              true, true, true,
              true, true, true,
              true, true, true,
              true, true, true]
imu0_queue_size: 10
imu0_differential: true
imu0_remove_gravitational_acceleration: true
